version: "3.7"
services:
#
  frontend:
    build: frontend/
    ports:
      - 80:80
    volumes:
      - ./frontend/src:/usr/local/apache2/htdocs/
    restart: always
#
  backend:
    build: backend/
    ports:
      - 5000:5000
    volumes:
      - ./backend/src/:/app/
    restart: always